# INSERT INTO curs(des_curs, titol_curs, url_curs) VALUES ('Access a dades','Modul 1','https://fpdual.jaumebalmes.net/');
# INSERT INTO curs(des_curs, titol_curs, url_curs) VALUES ('Programacio orientada a Objectes','Modul 2','https://fpdual.jaumebalmes.net/');
INSERT INTO curs(des_curs, titol_curs, url_curs) VALUES ('Base de dades','Modul 3','https://fpdual.jaumebalmes.net/');
INSERT INTO curs(des_curs, titol_curs, url_curs) VALUES ('Spring Boot','Modul 4','https://fpdual.jaumebalmes.net/');
INSERT INTO curs(des_curs, titol_curs, url_curs) VALUES ('Encriptacio','Modul 5','https://fpdual.jaumebalmes.net/');
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Baldam','Mignon',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Edmonstone','Ernestus',5);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Roslen','Yuri',2);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Muldowney','Juliette',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Bagnall','Martica',2);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Readman','Halette',5);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Archdeckne','Lita',4);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Jagg','Humfrid',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Willstrop','Benton',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Eslemont','Paddy',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Kitchener','Florance',2);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('De' 'Witt','Gustaf',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Collins','Raina',4);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('McMains','Diann',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Renachowski','Derby',5);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('De' 'Roberto','Wilone',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Cockett','Kylie',5);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Ruilton','Chaddie',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Eaglestone','Addia',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Pollak','Dania',4);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Britney','Cam',1);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Uttley','Brose',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Vinsen','Derwin',5);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Blakeborough','Eddie',3);
INSERT INTO student(estudiant_cognom, estudiant_nom, curs_cursid) VALUES ('Kadwallider','Guglielma',3);